"""Backward-compatible command-line entry point for the IMDb scraper."""

from imdb_scraper.advanced import (
    _advanced_worker,
    _attempt_advanced_links,
    _close_driver,
    _combine_advanced,
    _has_data,
    _is_network_error,
    _is_session_error,
    _links_from_df,
    _missing_stages,
    _status_records,
    _string_or_none,
    _write_status,
    extract_advanced_data,
    log_field_completeness,
)
from imdb_scraper.analysis import (
    _currency_symbol,
    _parse_money,
    _parse_release_dates,
    _parse_runtime_to_minutes,
    _release_date_has_day,
    _safe_list_len,
    _same_or_unknown_currency,
    compute_derived_columns,
    merge_data,
)
from imdb_scraper.browser import PageContentError, _wait_for_page_ready, clean_text, create_edge_driver
from imdb_scraper.cli import _parse_refresh_stages, main
from imdb_scraper.config import (
    ADVANCED_COLUMNS,
    ADVANCED_STAGES,
    ADVANCED_WORKERS,
    BASIC_COLUMNS,
    BLOCKED_RESOURCE_URLS,
    CHECKPOINT_INTERVAL,
    FULL_CREDITS_DEPARTMENTS,
    IMDB_BASE_URL,
    LOAD_MORE_BUTTON_TIMEOUT_SECONDS,
    LOAD_MORE_RESULT_TIMEOUT_SECONDS,
    LOAD_MORE_RETRY_PAUSE_SECONDS,
    NETWORK_BACKOFF_SECONDS,
    NETWORK_ERROR_THRESHOLD,
    PAGE_LOAD_TIMEOUT_SECONDS,
    PARENTAL_GUIDE_CATEGORIES,
    REQUIRED_CONTENT_TIMEOUT_SECONDS,
    SCRAPE_VERSION,
    SCRIPT_DIR,
    SCRIPT_TIMEOUT_SECONDS,
    STAGE_FIELDS,
    STATUS_COLUMNS,
    WORKER_RESULT_TIMEOUT_SECONDS,
    YEAR_PAUSE_SECONDS,
)
from imdb_scraper.extractors import (
    StageExtractionError,
    _advanced_row_template,
    _as_list,
    _content_title_id,
    _expected_title_id,
    _expand_release_info,
    _extract_advanced_row,
    _extract_advanced_stages,
    _extract_cast,
    _extract_json_ld,
    _extract_principal_credits,
    _is_expected_imdb_page,
    _is_missing_value,
    _iso8601_to_minutes,
    _next_content_data,
    _next_data,
    _normalize_imdb_url,
    _normalize_votes,
    _page_content_data,
    _page_soup,
    _persons,
    _text_in,
    _title_base_url,
    extract_full_credits,
    extract_links,
    extract_listing_metadata,
    extract_parental_guide,
    extract_release_info,
)
from imdb_scraper.pipeline import process_year, retry_failed_year
from imdb_scraper.storage import (
    append_attempt_log,
    log_advanced_timing_summary,
    now_iso,
    read_csv_fast,
    read_csv_or_empty,
    setup_directories,
    setup_logging,
    write_csv_safely,
    year_paths,
)


if __name__ == "__main__":
    main()
